#Format switch
Format = true

#testnet or mainnet
TestNet = false

#Directory for managing private key json files（default = "keystore/"）
KeystoreDir = ""

#RPC address
RpcIp = "127.0.0.1"

#RPC port
RpcPort = "23562"

#RPC TLS switch
RpcTLS = false

#If RpcTLS is on, you need to configure RpcCert
RpcCert = ""

#RPC username
RpcUser = ""

#RPC password
RpcPass = ""


