# testnet or mainnet
TestNet = true

# chain data directory
Data = "data"

# Logging switch
Logging = true

# P2P configuration
#Externale ip (default = "0.0.0.0")
ExternalIp = "0.0.0.0"

# Custom boot


# P2P port (default = "13561")
P2PPort="13567"


# RPC configuration
# (default = 13562)
RpcPort = "13568"

# (default = 13563)
HttpPort = "13569"

# RPC password
RpcUser = ""
RpcPass = ""

# TLS switch
RpcTLS = false

# If it is a block generating node, it needs to be configured
# Json file address of the address private key
KeyFile = "../wallet/keystore/aiAQ56a2nTmAxJ2Tycm8a3X8zYqs2NrDdUN.json"
# Password to decrypt the private key json file
KeyPass = "1"

