# testnet or mainnet
TestNet = true

# chain data directory
Data = "data"

# Logging switch
Logging = true

# P2P configuration
#Externale ip (default = "0.0.0.0")
ExternalIp = "0.0.0.0"

# Custom boot


# P2P port (default testnet = "13561", mainnet = "23561" )
P2PPort="13561"


# RPC configuration
# (default testnet = 13562, mainnet = 13562)
RpcPort = "13562"

# (default testnet = 23563, mainnet = 13562)
HttpPort = "13563"

RpcUser = ""
RpcPass = ""

# TLS switch
RpcTLS = false

# If it is a block generating node, it needs to be configured
# Json file address of the address private key
KeyFile = ""
# Password to decrypt the private key json file
KeyPass = ""

